RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Workshop DevSecOps AWS"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  editURL = ""
  description = "Workshop DevSecOps AWS"
  author = "Allyson Oliveira, Maria Ane Dias, Jo√£o Gabriel Carnevale e Daniel Garcia"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Languages]
[Languages.en]
title = "Workshop DevSecOps AWS"
weight = 1
languageName = "English"